name: Run 1TonBoys
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm start
